---
- name: 复制包到指定服务器(el6)
  unarchive:
    src: snmpel6.zip
    dest: /tmp/
  when: "(ansible_os_family == 'RedHat' or ansible_os_family == 'CentOS') and ansible_distribution_major_version == '6'"

- name: 复制包到指定服务器(el7)
  unarchive:
    src: snmpel7.zip
    dest: /tmp/
  when: "(ansible_os_family == 'RedHat' or ansible_os_family == 'CentOS') and ansible_distribution_major_version == '7'"

- name: 开始安装snmp
  command: "rpm -Uivh /tmp/snmp/*.rpm"