
# zabbix server 地址
server_ip: 127.0.0.1
# 配置文件存放地址

zabbix_el6: https://repo.zabbix.com/zabbix/4.0/rhel/6/x86_64/zabbix-release-4.0-1.el6.noarch.rpm
zabbix_el7: https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm