---
- name: 将rpm文件复制到远程服务器
  copy:
    dest: /
    src: files/rabbitmq-server-3.7.5-1.el6.noarch.rpm
- name: 安装rabbitmq
  shell: "rpm -ivh /rabbitmq-server-3.7.5-1.el6.noarch.rpm"
- name: 生成配置文件
  template:
    src: template/rabbitmq.j2
    dest: /etc/rabbitme/rabbitmq.config
- name: 复制插件配置文件
  copy:
    src: files/enabled_plugins
    dest: /etc/rabbitmq/
- name: 开启rabbitmq服务
  shell: "sh /usr/lib/rabbitmq/bin/rabbitmq-server"