---
- name: 将rpm文件复制到远程服务器
  copy:
    dest: /
    src: files/rabbitmq-server-3.7.5-1.el6.noarch.rpm
- name: 安装rabbitmq
  shell: "rpm -ivh /rabbitmq-server-3.7.5-1.el6.noarch.rpm"
- name: 生成配置文件
  template:
    src: template/rabbitmq.j2
    dest: /etc/rabbitme/rabbitmq.config
- name: Enables the rabbitmq_management plugin
  rabbitmq_plugin:
    names: rabbitmq_management
    state: enabled
- name: add user and set permission
  rabbitmq_user:
    user: '{{rabbitmq_username}}'
    password: '{{rabbitmq_password}}'
    permissions:
    - vhost: /
      configure_priv: .*
      read_priv: .*
      write_priv: .*
    state: present
- name: 启动rabbitmq服务
  service:
    name: rabbitmq-server
    enabled: yes
    state: started